title = "Knot"
md_path = "./docs/md"
html_path = "./docs/html"

[features]
search = true
next_previous_btns = true
view_raw_md = true
toc_sidebar = true

[styling]
main_col = "OrangeRed"
background_col = "Stone"
radius = "Standard"
